name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync with Hugging Face Space
        uses: nateraw/huggingface-sync-action@v0.0.4
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          huggingface_repo_id: anthonychuang/video-transcriber   # <-- corrected key
          repo_type: space                                       # <-- important
          space_sdk: gradio                                      # <-- matches your Space SDK
